## Preprocessing

In [3]:
pip install tensorflow

Collecting tensorflow
  Using cached tensorflow-2.6.2-cp36-cp36m-win_amd64.whl (423.3 MB)
Collecting absl-py~=0.10
  Using cached absl_py-0.15.0-py3-none-any.whl (132 kB)Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution -umpy (c:\users\erika\anaconda3\envs\pythondata\lib\site-packages)

Requirement already satisfied: numpy~=1.19.2 in c:\users\erika\anaconda3\envs\pythondata\lib\site-packages (from tensorflow) (1.19.5)
Collecting wrapt~=1.12.1
  Using cached wrapt-1.12.1-py3-none-any.whl
Collecting flatbuffers~=1.12.0
  Using cached flatbuffers-1.12-py2.py3-none-any.whl (15 kB)
Collecting h5py~=3.1.0
  Using cached h5py-3.1.0-cp36-cp36m-win_amd64.whl (2.7 MB)
Collecting google-pasta~=0.2
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
Collecting clang~=5.0
  Using cached clang-5.0-py3-none-any.whl
Requirement already satisfied: protobuf>=3.9.2 in c:\users\erika\anaconda3\envs\pythondata\lib\site-packages (from tensorflow) (3.19.4)
Requirement already satisfied: typing-extensions~=3.7.4 in c:\users\erika\anaconda3\envs\pythondata\lib\site-packages (from tensorflow) (3.7.4.3)
Requirement already satisfied: wheel~=0.35 in c:\users\erika\anaconda3\envs\pythondata\lib\site-packages (from tensorflow) (0.37.1)
Collecting tensorboard<2.7,>=2.6.0
  Using cached tensorboard-2.6.0-py3-none-any.whl (5.6 MB)
Collecting tensorflow-estimator<2.7,>=2.6.0
  Using cached tensorflow_estimator-2.6.0-py2.py3-none-any.whl (462 kB)
Collecting astunparse~=1.6.3
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Collecting keras<2.7,>=2.6.0
  Using cached keras-2.6.0-py2.py3-none-any.whl (1.3 MB)
Collecting grpcio<2.0,>=1.37.0
  Using cached grpcio-1.44.0-cp36-cp36m-win_amd64.whl (3.4 MB)
Collecting gast==0.4.0
  Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
Collecting termcolor~=1.1.0
  Using cached termcolor-1.1.0-py3-none-any.whl
Collecting keras-preprocessing~=1.1.2
  Using cached Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
Collecting opt-einsum~=3.3.0
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
Requirement already satisfied: six~=1.15.0 in c:\users\erika\anaconda3\envs\pythondata\lib\site-packages (from tensorflow) (1.15.0)
Collecting cached-property
  Using cached cached_property-1.5.2-py2.py3-none-any.whl (7.6 kB)
Collecting google-auth-oauthlib<0.5,>=0.4.1
  Using cached google_auth_oauthlib-0.4.6-py2.py3-none-any.whl (18 kB)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\erika\anaconda3\envs\pythondata\lib\site-packages (from tensorboard<2.7,>=2.6.0->tensorflow) (2.26.0)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in c:\users\erika\anaconda3\envs\pythondata\lib\site-packages (from tensorboard<2.7,>=2.6.0->tensorflow) (0.6.1)
Requirement already satisfied: google-auth<2,>=1.6.3 in c:\users\erika\anaconda3\envs\pythondata\lib\site-packages (from tensorboard<2.7,>=2.6.0->tensorflow) (1.35.0)
Requirement already satisfied: werkzeug>=0.11.15 in c:\users\erika\anaconda3\envs\pythondata\lib\site-packages (from tensorboard<2.7,>=2.6.0->tensorflow) (2.0.2)
Requirement already satisfied: setuptools>=41.0.0 in c:\users\erika\anaconda3\envs\pythondata\lib\site-packages (from tensorboard<2.7,>=2.6.0->tensorflow) (47.3.1.post20200622)

WARNING: Ignoring invalid distribution -umpy (c:\users\erika\anaconda3\envs\pythondata\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\erika\anaconda3\envs\pythondata\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\erika\anaconda3\envs\pythondata\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\erika\anaconda3\envs\pythondata\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\erika\anaconda3\envs\pythondata\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\erika\anaconda3\envs\pythondata\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\erika\anaconda3\envs\pythondata\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\erika\anaconda3\envs\pythondata\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\erika\anaconda3\envs\pythondata\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\erika\anaconda3\envs\pythondata\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\erika\anaconda3\envs\pythondata\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\erika\anaconda3\envs\pythondata\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\erika\anaconda3\envs\pythondata\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\erika\anaconda3\envs\pythondata\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\erika\anaconda3\envs\pythondata\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\erika\anaconda3\envs\pythondata\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\erika\anaconda3\envs\pythondata\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\erika\anaconda3\envs\pythondata\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\erika\anaconda3\envs\pythondata\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\erika\anaconda3\envs\pythondata\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\erika\anaconda3\envs\pythondata\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\erika\anaconda3\envs\pythondata\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\erika\anaconda3\envs\pythondata\lib\site-packages)

Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in c:\users\erika\anaconda3\envs\pythondata\lib\site-packages (from tensorboard<2.7,>=2.6.0->tensorflow) (1.8.1)
Collecting markdown>=2.6.8
  Using cached Markdown-3.3.6-py3-none-any.whl (97 kB)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\users\erika\anaconda3\envs\pythondata\lib\site-packages (from google-auth<2,>=1.6.3->tensorboard<2.7,>=2.6.0->tensorflow) (4.8)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\erika\anaconda3\envs\pythondata\lib\site-packages (from google-auth<2,>=1.6.3->tensorboard<2.7,>=2.6.0->tensorflow) (0.2.8)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in c:\users\erika\anaconda3\envs\pythondata\lib\site-packages (from google-auth<2,>=1.6.3->tensorboard<2.7,>=2.6.0->tensorflow) (4.2.4)
Requirement already satisfied: requests-oauthlib>=0.7.0 in c:\users\erika\anaconda3\envs\pythondata\lib\site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.7,>=2.6.0->tensorflow) (1.3.1)
Requirement already satisfied: importlib-metadata>=4.4 in c:\users\erika\anaconda3\envs\pythondata\lib\site-packages (from markdown>=2.6.8->tensorboard<2.7,>=2.6.0->tensorflow) (4.8.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\erika\anaconda3\envs\pythondata\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.7,>=2.6.0->tensorflow) (2.0.7)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\erika\anaconda3\envs\pythondata\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.7,>=2.6.0->tensorflow) (1.26.7)
Requirement already satisfied: idna<4,>=2.5 in c:\users\erika\anaconda3\envs\pythondata\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.7,>=2.6.0->tensorflow) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\erika\anaconda3\envs\pythondata\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.7,>=2.6.0->tensorflow) (2020.6.20)
Requirement already satisfied: dataclasses in c:\users\erika\anaconda3\envs\pythondata\lib\site-packages (from werkzeug>=0.11.15->tensorboard<2.7,>=2.6.0->tensorflow) (0.8)
Requirement already satisfied: zipp>=0.5 in c:\users\erika\anaconda3\envs\pythondata\lib\site-packages (from importlib-metadata>=4.4->markdown>=2.6.8->tensorboard<2.7,>=2.6.0->tensorflow) (3.3.1)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\users\erika\anaconda3\envs\pythondata\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<2,>=1.6.3->tensorboard<2.7,>=2.6.0->tensorflow) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in c:\users\erika\anaconda3\envs\pythondata\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.7,>=2.6.0->tensorflow) (3.2.0)
Installing collected packages: markdown, grpcio, google-auth-oauthlib, cached-property, absl-py, wrapt, termcolor, tensorflow-estimator, tensorboard, opt-einsum, keras-preprocessing, keras, h5py, google-pasta, gast, flatbuffers, clang, astunparse, tensorflow
Successfully installed absl-py-0.15.0 astunparse-1.6.3 cached-property-1.5.2 clang-5.0 flatbuffers-1.12 gast-0.4.0 google-auth-oauthlib-0.4.6 google-pasta-0.2.0 grpcio-1.44.0 h5py-3.1.0 keras-2.6.0 keras-preprocessing-1.1.2 markdown-3.3.6 opt-einsum-3.3.0 tensorboard-2.6.0 tensorflow-2.6.2 tensorflow-estimator-2.6.0 termcolor-1.1.0 wrapt-1.12.1

In [25]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("Resources/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [26]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns = ['EIN', 'NAME'])
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [27]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [28]:
# Look at APPLICATION_TYPE value counts for binning
app_type_values = application_df['APPLICATION_TYPE'].value_counts()
app_type_values

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T14        3
T25        3
T15        2
T29        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [29]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(app_type_values[app_type_values < 500].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [30]:
# Look at CLASSIFICATION value counts for binning
classification_binning = application_df['CLASSIFICATION'].value_counts()
classification_binning

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C8210        1
C5200        1
C4200        1
C1732        1
C2190        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [31]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_values = classification_binning[classification_binning>1]
classification_values

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C2300       32
C7200       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1278       10
C1238       10
C1237        9
C1235        9
C7210        7
C1720        6
C4100        6
C2400        6
C1257        5
C1600        5
C0           3
C1260        3
C2710        3
C3200        2
C1267        2
C1246        2
C1234        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [32]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(classification_binning[classification_binning < 1000].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [34]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df,dtype=float)
application_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [41]:
# Split our preprocessed data into our features and target arrays
y = application_df['IS_SUCCESSFUL'].values
X = application_df.drop(['IS_SUCCESSFUL'], axis=1).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state = 42)

In [42]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [47]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
nn_model = tf.keras.models.Sequential()

# First hidden layer
nn_model.add(
    tf.keras.layers.Dense(units=80, input_dim=len(X_train[0]), activation="relu"))

# Second hidden layer
nn_model.add(tf.keras.layers.Dense(units=30, activation="relu"))

# Output layer
nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))


# Check the structure of the model
nn_model.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_15 (Dense)             (None, 80)                3520
_________________________________________________________________
dense_16 (Dense)             (None, 30)                2430
_________________________________________________________________
dense_17 (Dense)             (None, 1)                 31
=================================================================
Total params: 5,981
Trainable params: 5,981
Non-trainable params: 0
_________________________________________________________________

In [48]:
# Compile the model
nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [49]:
# Train the model
fit_model = nn_model.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 5s 4ms/step - loss: 0.5720 - accuracy: 0.7195
Epoch 2/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5551 - accuracy: 0.7293
Epoch 3/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5521 - accuracy: 0.7305
Epoch 4/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5507 - accuracy: 0.7308
Epoch 5/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5485 - accuracy: 0.7304
Epoch 6/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5476 - accuracy: 0.7326
Epoch 7/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5471 - accuracy: 0.7316
Epoch 8/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5463 - accuracy: 0.7324
Epoch 9/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5458 - accuracy: 0.7322
Epoch 10/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5452 - accuracy: 0.7336
Epoch 11/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5448 - accuracy: 0.7331
Epoch 12/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5446 - accuracy: 0.7335
Epoch 13/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5437 - accuracy: 0.7334
Epoch 14/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5444 - accuracy: 0.7343
Epoch 15/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5433 - accuracy: 0.7346
Epoch 16/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5427 - accuracy: 0.7346
Epoch 17/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5429 - accuracy: 0.7345
Epoch 18/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5428 - accuracy: 0.7345
Epoch 19/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5421 - accuracy: 0.7359
Epoch 20/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5418 - accuracy: 0.7350
Epoch 21/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5414 - accuracy: 0.7355
Epoch 22/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5415 - accuracy: 0.7365
Epoch 23/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5413 - accuracy: 0.7357
Epoch 24/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5414 - accuracy: 0.7369
Epoch 25/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5405 - accuracy: 0.7362
Epoch 26/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5403 - accuracy: 0.7364
Epoch 27/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5402 - accuracy: 0.7352
Epoch 28/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5402 - accuracy: 0.7366: 0s - loss: 0.5404 - accuracy: 0.
Epoch 29/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5401 - accuracy: 0.7361
Epoch 30/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5399 - accuracy: 0.7362
Epoch 31/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5400 - accuracy: 0.7363
Epoch 32/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5392 - accuracy: 0.7376
Epoch 33/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5394 - accuracy: 0.7373
Epoch 34/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5393 - accuracy: 0.7370
Epoch 35/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5387 - accuracy: 0.7373
Epoch 36/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5386 - accuracy: 0.7377
Epoch 37/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5387 - accuracy: 0.7376
Epoch 38/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5383 - accuracy: 0.7384
Epoch 39/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5384 - accuracy: 0.7388
Epoch 40/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5384 - accuracy: 0.7379
Epoch 41/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5383 - accuracy: 0.7371
Epoch 42/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5381 - accuracy: 0.7370
Epoch 43/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5379 - accuracy: 0.7384
Epoch 44/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5377 - accuracy: 0.7390
Epoch 45/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5374 - accuracy: 0.7381
Epoch 46/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5376 - accuracy: 0.7385
Epoch 47/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5374 - accuracy: 0.7376
Epoch 48/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5374 - accuracy: 0.7387
Epoch 49/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5372 - accuracy: 0.7391
Epoch 50/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5374 - accuracy: 0.7390
Epoch 51/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5371 - accuracy: 0.7406
Epoch 52/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5369 - accuracy: 0.7389
Epoch 53/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5369 - accuracy: 0.7395
Epoch 54/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5368 - accuracy: 0.7388
Epoch 55/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5365 - accuracy: 0.7387
Epoch 56/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5370 - accuracy: 0.7391
Epoch 57/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5362 - accuracy: 0.7397
Epoch 58/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5365 - accuracy: 0.7395
Epoch 59/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5362 - accuracy: 0.7395
Epoch 60/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5363 - accuracy: 0.7386
Epoch 61/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5367 - accuracy: 0.7395
Epoch 62/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5358 - accuracy: 0.7399
Epoch 63/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5364 - accuracy: 0.7389
Epoch 64/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5362 - accuracy: 0.7387
Epoch 65/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5357 - accuracy: 0.7396
Epoch 66/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5356 - accuracy: 0.7393
Epoch 67/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5359 - accuracy: 0.7389
Epoch 68/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5357 - accuracy: 0.7393
Epoch 69/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5358 - accuracy: 0.7397
Epoch 70/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5358 - accuracy: 0.7388
Epoch 71/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5355 - accuracy: 0.7399
Epoch 72/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5353 - accuracy: 0.7398
Epoch 73/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5352 - accuracy: 0.7396
Epoch 74/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5354 - accuracy: 0.7389
Epoch 75/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5351 - accuracy: 0.7395
Epoch 76/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5353 - accuracy: 0.7395: 0s - loss: 0.535
Epoch 77/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5353 - accuracy: 0.7399
Epoch 78/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5348 - accuracy: 0.7397
Epoch 79/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5347 - accuracy: 0.7404
Epoch 80/100

804/804 [==============================] - 3s 3ms/step - loss: 0.5348 - accuracy: 0.7397
Epoch 81/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5351 - accuracy: 0.7400
Epoch 82/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5349 - accuracy: 0.7398
Epoch 83/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5349 - accuracy: 0.7393
Epoch 84/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5347 - accuracy: 0.7393
Epoch 85/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5346 - accuracy: 0.7401
Epoch 86/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5344 - accuracy: 0.7399
Epoch 87/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5349 - accuracy: 0.7405
Epoch 88/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5343 - accuracy: 0.7400
Epoch 89/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5344 - accuracy: 0.7398
Epoch 90/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5344 - accuracy: 0.7396
Epoch 91/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5346 - accuracy: 0.7403
Epoch 92/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5348 - accuracy: 0.7385
Epoch 93/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5343 - accuracy: 0.7397
Epoch 94/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5344 - accuracy: 0.7397
Epoch 95/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5340 - accuracy: 0.7395
Epoch 96/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5341 - accuracy: 0.7395
Epoch 97/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5338 - accuracy: 0.7402
Epoch 98/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5345 - accuracy: 0.7405
Epoch 99/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5338 - accuracy: 0.7401
Epoch 100/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5338 - accuracy: 0.7397

In [51]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5641 - accuracy: 0.7279
Loss: 0.5640614628791809, Accuracy: 0.7279300093650818

In [52]:
# Export our model to HDF5 file
nn_model.save("AlphabetSoupCharity.h5")